# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty
relative_permalinks: true

# http://jekyllrb.com/docs/github-pages/#project-page-url-structure
#baseurl: https://guillaumelobet.github.io/
baseurl: /perso/ # for local testing

# Setup
title:            Guillaume's Blog
paginate:         1
author:
  name:           Guillaume Lobet
  url:            https://twitter.com/guillaumelobet
  email:          guillaume.lobet@ulg.ac.be
