  body: >
        
    First and foremost, we are an open science lab. There are several major facets to this, but the core is: the way this lab operates is grounded in my personal belief that participation in science is a public act, and done in the public good. Science allows us to be part of something bigger, and to foster a healthy, collaborative and truly inclusive scientific enterprise, it’s essential that we give back at least as much as we take from the community. We could get down into the weeds about specific tools and techniques that we use in our open science infrastructure here, but those tools are used to support these values, they themselves are not the values.
  
    
    We also believe the outputs and production of public science should not be used to enrich a few for profit private companies. We believe non-profit and society-lead journals and platforms have a higher value for the scientific community and the public.
    
    
    Therefore, what we commit to do, as open scientists, is: 
    
    - Make supporting research data freely available whenever possible, to support future use in meta-analyses, reviews, and revisitations of our work.
    
    - Respect privacy and confidentiality in cases where data or research products contain sensitive information. Do no harm.
    
    - Produce and share reproducible, re-usable data manipulation and analysis code, so people can understand our assumptions and workflows, and so future scientists can learn from our efforts without duplicating them.
    
    - Publish final manuscripts AND intermediate research products in the most accessible formats available to us.
    
    - As much as possible, give priority to non-profit, community-lead, gold or green open-access journals (in that order). Publish results as preprints as often as possible. 
    
    - Seek out expertise from conventional and unconventional stakeholders in our work. Invite comment and participation. Welcome feedback.
    
    - Acknowledge contributions to our work, and cite the ideas of others. Don’t pretend we work in a vacuum.
    
    - Act as ambassadors of open science, and science in general, to the broader scientific community and the world. Help people see what we do, but respect the constraints others must work under. 
